version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/my-repo

jobs:
  prepare-dependencies:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - persist_to_workspace:
          root: .
          paths:
            - .

  check-eslint:
    executor: my-executor
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Check ESLint
          command:
              yarn lint

  # build-then-deploy:
  #   executor: my-executor
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: Build
  #         command: yarn build
  #     - run:
  #         name: Deploy Master to Firebase
  #         command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - prepare-dependencies
      - check-eslint:
          requires: 
            - prepare-dependencies 
      # - build-then-deploy:
      #     requires: 
      #       - prepare-dependencies
      #     filters:
      #       branches:
      #         only: master
